import { Poppins } from '@next/font/google';
import type { Metadata } from 'next';
import { unstable_noStore as noStore } from 'next/cache';

import '../styles/globals.css';

import { useAuth } from '@/hooks/use-auth';

import { Toaster } from '@/components/ui/toaster';

import StoreInitializer from '@/store/StoreInitializer';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  noStore();

  const { fetchUser } = useAuth();
  const user = await fetchUser();
  return (
    <html lang="en" className={` bg-blue-900 ${poppins.className}`}>
      <body className="max-w-md mx-auto bg-neutral-900 min-h-screen">
        <StoreInitializer auth={user} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
